<?php return array (
  /*  0 =>
        array (
            'id' => 0,
            'title' => '数据库',
            'icon' => 'layui-icon layui-icon-template-1',
            'key' => 'database',
            'pid' => 0,
            'created_at' => '2023-08-19 15:08:03',
            'updated_at' => '2023-12-09 15:55:53',
            'href' => NULL,
            'type' => 0,
            'weight' => 1001,
            'name' => '数据库',
            'value' => '1',
            'children' =>
                array (
                    0 =>
                        array (
                            'id' => 1,
                            'title' => '所有表',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\TableController',
                            'pid' => 1,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/table/index',
                            'type' => 1,
                            'weight' => 800,
                            'name' => '所有表',
                            'value' => '2',
                            'children' =>
                                array (
                                ),
                        ),
                ),
        ),*/
    1 =>
        array (
            'id' => 2,
            'title' => '权限管理',
            'icon' => 'layui-icon layui-icon-vercode',
            'key' => 'auth',
            'pid' => 0,
            'created_at' => '2023-08-19 15:08:03',
            'updated_at' => '2023-08-19 15:08:03',
            'href' => NULL,
            'type' => 0,
            'weight' => 900,
            'name' => '权限管理',
            'value' => '3',
            'children' =>
                array (
                    0 =>
                        array (
                            'id' => 3,
                            'title' => '账户管理',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\AdminController',
                            'pid' => 3,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/admin/index',
                            'type' => 1,
                            'weight' => 1000,
                            'name' => '账户管理',
                            'value' => '4',
                            'children' =>
                                array (
                                ),
                        ),
                    1 =>
                        array (
                            'id' => 4,
                            'title' => '角色管理',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\RoleController',
                            'pid' => 3,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/role/index',
                            'type' => 1,
                            'weight' => 900,
                            'name' => '角色管理',
                            'value' => '5',
                            'children' =>
                                array (
                                ),
                        ),
                    2 =>
                        array (
                            'id' => 5,
                            'title' => '菜单管理',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\RuleController',
                            'pid' => 3,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/rule/index',
                            'type' => 1,
                            'weight' => 800,
                            'name' => '菜单管理',
                            'value' => '6',
                            'children' =>
                                array (
                                ),
                        ),
                ),
        ),
    2 =>
        array (
            'id' => 6,
            'title' => '会员管理',
            'icon' => 'layui-icon layui-icon-username',
            'key' => 'user',
            'pid' => 0,
            'created_at' => '2023-08-19 15:08:03',
            'updated_at' => '2023-08-19 15:08:03',
            'href' => NULL,
            'type' => 0,
            'weight' => 800,
            'name' => '会员管理',
            'value' => '7',
            'children' =>
                array (
                    0 =>
                        array (
                            'id' => 7,
                            'title' => '用户',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\UserController',
                            'pid' => 7,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/user/index',
                            'type' => 1,
                            'weight' => 800,
                            'name' => '用户',
                            'value' => '8',
                            'children' =>
                                array (
                                ),
                        ),
                ),
        ),
    3 =>
        array (
            'id' => 8,
            'title' => '通用设置',
            'icon' => 'layui-icon layui-icon-set',
            'key' => 'common',
            'pid' => 0,
            'created_at' => '2023-08-19 15:08:03',
            'updated_at' => '2023-08-19 15:08:03',
            'href' => NULL,
            'type' => 0,
            'weight' => 700,
            'name' => '通用设置',
            'value' => '9',
            'children' =>
                array (
                    0 =>
                        array (
                            'id' => 9,
                            'title' => '个人资料',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\AccountController',
                            'pid' => 9,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/account/index',
                            'type' => 1,
                            'weight' => 800,
                            'name' => '个人资料',
                            'value' => '10',
                            'children' =>
                                array (
                                ),
                        ),
                    1 =>
                        array (
                            'id' => 10,
                            'title' => '附件管理',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\UploadController',
                            'pid' => 9,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/upload/index',
                            'type' => 1,
                            'weight' => 700,
                            'name' => '附件管理',
                            'value' => '11',
                            'children' =>
                                array (
                                ),
                        ),
                    2 =>
                        array (
                            'id' => 11,
                            'title' => '字典设置',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\DictController',
                            'pid' => 9,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/dict/index',
                            'type' => 1,
                            'weight' => 600,
                            'name' => '字典设置',
                            'value' => '12',
                            'children' =>
                                array (
                                ),
                        ),
                    3 =>
                        array (
                            'id' => 12,
                            'title' => '系统设置',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\ConfigController',
                            'pid' => 9,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/config/index',
                            'type' => 1,
                            'weight' => 500,
                            'name' => '系统设置',
                            'value' => '13',
                            'children' =>
                                array (
                                ),
                        ),
                ),
        ),
    4 =>
        array (
            'id' => 13,
            'title' => '插件管理',
            'icon' => 'layui-icon layui-icon-app',
            'key' => 'plugin',
            'pid' => 0,
            'created_at' => '2023-08-19 15:08:03',
            'updated_at' => '2023-08-19 15:08:03',
            'href' => NULL,
            'type' => 0,
            'weight' => 600,
            'name' => '插件管理',
            'value' => '14',
            'children' =>
                array (
                    0 =>
                        array (
                            'id' => 14,
                            'title' => '应用插件',
                            'icon' => '',
                            'key' => 'plugin\\admin\\app\\controller\\PluginController',
                            'pid' => 14,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '/app/admin/plugin/index',
                            'type' => 1,
                            'weight' => 800,
                            'name' => '应用插件',
                            'value' => '15',
                            'children' =>
                                array (
                                ),
                        ),
                ),
        ),
    5 =>
        array (
            'id' => 15,
            'title' => '示例页面',
            'icon' => 'layui-icon layui-icon-template',
            'key' => 'demos',
            'pid' => 0,
            'created_at' => '2023-08-19 15:08:03',
            'updated_at' => '2023-12-12 15:04:57',
            'href' => NULL,
            'type' => 0,
            'weight' => 400,
            'name' => '示例页面',
            'value' => '18',
            'children' =>
                array (
                    0 =>
                        array (
                            'id' => 16,
                            'title' => '工作空间',
                            'icon' => 'layui-icon layui-icon-console',
                            'key' => 'demo/workspace',
                            'pid' => 18,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-12-12 15:34:30',
                            'href' => '',
                            'type' => 0,
                            'weight' => 0,
                            'name' => '工作空间',
                            'value' => '19',
                            'children' =>
                                array (
                                    0 =>
                                        array (
                                            'id' => 17,
                                            'title' => '工作台',
                                            'icon' => 'layui-icon layui-icon-util',
                                            'key' => 'demo/workspace/workbench',
                                            'pid' => 19,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-12-12 15:35:40',
                                            'href' => '/app/admin/demos?demo=workspace/workbench',
                                            'type' => 1,
                                            'weight' => 10,
                                            'name' => '工作台',
                                            'value' => '20',
                                        ),
                                    1 =>
                                        array (
                                            'id' => 18,
                                            'title' => '控制台',
                                            'icon' => 'layui-icon layui-icon-engine',
                                            'key' => 'demo/workspace/console',
                                            'pid' => 19,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-12-12 15:37:04',
                                            'href' => '/app/admin/demos?demo=workspace/console',
                                            'type' => 1,
                                            'weight' => 8,
                                            'name' => '控制台',
                                            'value' => '21',
                                        ),
                                    2 =>
                                        array (
                                            'id' => 19,
                                            'title' => '分析页',
                                            'icon' => 'layui-icon layui-icon-chart-screen',
                                            'key' => 'demo/workspace/analysis',
                                            'pid' => 19,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=workspace/analysis',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '分析页',
                                            'value' => '22',
                                        ),
                                    3 =>
                                        array (
                                            'id' => 20,
                                            'title' => '监控页',
                                            'icon' => 'layui-icon layui-icon-find-fill',
                                            'key' => 'demo/workspace/monitor',
                                            'pid' => 19,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=workspace/monitor',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '监控页',
                                            'value' => '23',
                                        ),
                                ),
                        ),
                    1 =>
                        array (
                            'id' => 21,
                            'title' => '表单页面',
                            'icon' => 'layui-icon layui-icon-table',
                            'key' => 'demo/form',
                            'pid' => 18,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '',
                            'type' => 0,
                            'weight' => 0,
                            'name' => '表单页面',
                            'value' => '24',
                            'children' =>
                                array (
                                    0 =>
                                        array (
                                            'id' => 22,
                                            'title' => '基础表单',
                                            'icon' => 'layui-icon layui-icon-form',
                                            'key' => 'demo/form/base',
                                            'pid' => 24,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=form/base',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '基础表单',
                                            'value' => '25',
                                        ),
                                    1 =>
                                        array (
                                            'id' => 23,
                                            'title' => '复杂表单',
                                            'icon' => 'layui-icon layui-icon-form',
                                            'key' => 'demo/form/intricate',
                                            'pid' => 24,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=form/intricate',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '复杂表单',
                                            'value' => '26',
                                        ),
                                    2 =>
                                        array (
                                            'id' => 24,
                                            'title' => '分步表单',
                                            'icon' => 'layui-icon layui-icon-form',
                                            'key' => 'demo/form/step',
                                            'pid' => 24,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=form/step',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '分步表单',
                                            'value' => '27',
                                        ),
                                    3 =>
                                        array (
                                            'id' => 25,
                                            'title' => '查询列表',
                                            'icon' => 'layui-icon layui-icon-search',
                                            'key' => 'demo/table/base',
                                            'pid' => 24,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=table/base',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '查询列表',
                                            'value' => '28',
                                        ),
                                    4 =>
                                        array (
                                            'id' => 26,
                                            'title' => '卡片列表',
                                            'icon' => 'layui-icon layui-icon-file-b',
                                            'key' => 'demo/table/card',
                                            'pid' => 24,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=table/card',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '卡片列表',
                                            'value' => '29',
                                        ),
                                    5 =>
                                        array (
                                            'id' => 27,
                                            'title' => '项目列表',
                                            'icon' => 'layui-icon layui-icon-templeate-one',
                                            'key' => 'demo/table/project',
                                            'pid' => 24,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=table/project',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '项目列表',
                                            'value' => '30',
                                        ),
                                    6 =>
                                        array (
                                            'id' => 28,
                                            'title' => '文章列表',
                                            'icon' => 'layui-icon layui-icon-carousel',
                                            'key' => 'demo/table/article',
                                            'pid' => 24,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=table/article',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '文章列表',
                                            'value' => '31',
                                        ),
                                ),
                        ),
                    2 =>
                        array (
                            'id' => 29,
                            'title' => '外链页面',
                            'icon' => 'layui-icon layui-icon-link',
                            'key' => 'demo/page',
                            'pid' => 18,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '',
                            'type' => 0,
                            'weight' => 0,
                            'name' => '外链页面',
                            'value' => '41',
                            'children' =>
                                array (
                                    0 =>
                                        array (
                                            'id' => 30,
                                            'title' => '弹层外链',
                                            'icon' => 'layui-icon layui-icon-home',
                                            'key' => 'demo/app/admin',
                                            'pid' => 41,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-12-12 16:34:23',
                                            'href' => '/app/admin',
                                            'type' => 3,
                                            'weight' => 0,
                                            'name' => '弹层外链',
                                            'value' => '42',
                                        ),
                                    1 =>
                                        array (
                                            'id' => 31,
                                            'title' => '原生跳转',
                                            'icon' => 'layui-icon layui-icon-layouts',
                                            'key' => 'demo/http://www.baidu.com',
                                            'pid' => 41,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-12-12 16:34:27',
                                            'href' => 'http://www.baidu.com',
                                            'type' => 4,
                                            'weight' => 0,
                                            'name' => '原生跳转',
                                            'value' => '43',
                                        ),
                                ),
                        ),
                    3 =>
                        array (
                            'id' => 32,
                            'title' => '内置指令',
                            'icon' => 'layui-icon layui-icon-test',
                            'key' => 'demo/directive',
                            'pid' => 18,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '',
                            'type' => 0,
                            'weight' => 0,
                            'name' => '内置指令',
                            'value' => '44',
                            'children' =>
                                array (
                                    0 =>
                                        array (
                                            'id' => 33,
                                            'title' => '内置指令',
                                            'icon' => 'layui-icon layui-icon-template',
                                            'key' => 'demo/directive/index',
                                            'pid' => 44,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=directive/index',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '内置指令',
                                            'value' => '45',
                                        ),
                                ),
                        ),
                    4 =>
                        array (
                            'id' => 34,
                            'title' => '结果页面',
                            'icon' => 'layui-icon layui-icon-template',
                            'key' => 'demo/result',
                            'pid' => 18,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '',
                            'type' => 0,
                            'weight' => 0,
                            'name' => '结果页面',
                            'value' => '47',
                            'children' =>
                                array (
                                    0 =>
                                        array (
                                            'id' => 35,
                                            'title' => '失败页面',
                                            'icon' => 'layui-icon layui-icon-error',
                                            'key' => 'demo/result/failure',
                                            'pid' => 47,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-12-12 16:41:54',
                                            'href' => '/app/admin/demos?demo=result/failure',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '失败页面',
                                            'value' => '48',
                                        ),
                                    1 =>
                                        array (
                                            'id' => 36,
                                            'title' => '成功页面',
                                            'icon' => 'layui-icon layui-icon-success',
                                            'key' => 'demo/result/success',
                                            'pid' => 47,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=result/success',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '成功页面',
                                            'value' => '49',
                                        ),
                                ),
                        ),
                    5 =>
                        array (
                            'id' => 37,
                            'title' => '错误页面',
                            'icon' => 'layui-icon layui-icon-unlink',
                            'key' => 'demo/error',
                            'pid' => 18,
                            'created_at' => '2023-08-19 15:08:03',
                            'updated_at' => '2023-08-19 15:08:03',
                            'href' => '',
                            'type' => 0,
                            'weight' => 0,
                            'name' => '错误页面',
                            'value' => '50',
                            'children' =>
                                array (
                                    0 =>
                                        array (
                                            'id' => 38,
                                            'title' => '401',
                                            'icon' => 'layui-icon layui-icon-not-found',
                                            'key' => 'demo/error/401',
                                            'pid' => 50,
                                            'created_at' => '-0001-11-30 00:00:00',
                                            'updated_at' => '-0001-11-30 00:00:00',
                                            'href' => '/app/admin/demos?demo=error/401',
                                            'type' => 1,
                                            'weight' => 10,
                                            'name' => '401',
                                            'value' => '199',
                                        ),
                                    1 =>
                                        array (
                                            'id' => 39,
                                            'title' => '403',
                                            'icon' => 'layui-icon layui-icon-not-found',
                                            'key' => 'demo/error/403',
                                            'pid' => 50,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=error/403',
                                            'type' => 1,
                                            'weight' => 8,
                                            'name' => '403',
                                            'value' => '51',
                                        ),
                                    2 =>
                                        array (
                                            'id' => 40,
                                            'title' => '404',
                                            'icon' => 'layui-icon layui-icon-not-found',
                                            'key' => 'demo/error/404',
                                            'pid' => 50,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=error/404',
                                            'type' => 1,
                                            'weight' => 7,
                                            'name' => '404',
                                            'value' => '52',
                                        ),
                                    3 =>
                                        array (
                                            'id' => 41,
                                            'title' => '500',
                                            'icon' => 'layui-icon layui-icon-not-found',
                                            'key' => 'demo/error/500',
                                            'pid' => 50,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-08-19 15:08:03',
                                            'href' => '/app/admin/demos?demo=error/500',
                                            'type' => 1,
                                            'weight' => 4,
                                            'name' => '500',
                                            'value' => '53',
                                        ),
                                ),
                        ),
                    6 =>
                        array (
                            'id' => 42,
                            'title' => '系统管理',
                            'icon' => 'layui-icon layui-icon-set-fill',
                            'key' => 'demo/system',
                            'pid' => 18,
                            'created_at' => '2023-08-19 15:08:04',
                            'updated_at' => '2023-08-19 15:08:04',
                            'href' => '',
                            'type' => 0,
                            'weight' => 0,
                            'name' => '系统管理',
                            'value' => '54',
                            'children' =>
                                array (
                                    0 =>
                                        array (
                                            'id' => 43,
                                            'title' => '用户管理',
                                            'icon' => 'layui-icon layui-icon-user',
                                            'key' => 'demo/system/user',
                                            'pid' => 54,
                                            'created_at' => '2023-08-19 15:08:04',
                                            'updated_at' => '2023-08-19 15:08:04',
                                            'href' => '/app/admin/demos?demo=system/user',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '用户管理',
                                            'value' => '55',
                                        ),
                                    1 =>
                                        array (
                                            'id' => 44,
                                            'title' => '角色管理',
                                            'icon' => 'layui-icon layui-icon-user',
                                            'key' => 'demo/system/role',
                                            'pid' => 54,
                                            'created_at' => '2023-08-19 15:08:04',
                                            'updated_at' => '2023-08-19 15:08:04',
                                            'href' => '/app/admin/demos?demo=system/role',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '角色管理',
                                            'value' => '56',
                                        ),
                                    2 =>
                                        array (
                                            'id' => 45,
                                            'title' => '菜单管理',
                                            'icon' => 'layui-icon layui-icon-spread-left',
                                            'key' => 'demo/system/menu',
                                            'pid' => 54,
                                            'created_at' => '2023-08-19 15:08:04',
                                            'updated_at' => '2023-08-19 15:08:04',
                                            'href' => '/app/admin/demos?demo=system/menu',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '菜单管理',
                                            'value' => '57',
                                        ),
                                    3 =>
                                        array (
                                            'id' => 46,
                                            'title' => '机构管理',
                                            'icon' => 'layui-icon layui-icon-transfer',
                                            'key' => 'demo/system/organization',
                                            'pid' => 54,
                                            'created_at' => '2023-08-19 15:08:04',
                                            'updated_at' => '2023-08-19 15:08:04',
                                            'href' => '/app/admin/demos?demo=system/organization',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '机构管理',
                                            'value' => '58',
                                        ),
                                    4 =>
                                        array (
                                            'id' => 47,
                                            'title' => '字典管理',
                                            'icon' => 'layui-icon layui-icon-read',
                                            'key' => 'demo/system/dictionary',
                                            'pid' => 54,
                                            'created_at' => '2023-08-19 15:08:04',
                                            'updated_at' => '2023-08-19 15:08:04',
                                            'href' => '/app/admin/demos?demo=system/dictionary',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '字典管理',
                                            'value' => '59',
                                        ),
                                    5 =>
                                        array (
                                            'id' => 48,
                                            'title' => '文件管理',
                                            'icon' => 'layui-icon layui-icon-file',
                                            'key' => 'demo/system/file',
                                            'pid' => 54,
                                            'created_at' => '2023-08-19 15:08:04',
                                            'updated_at' => '2023-08-19 15:08:04',
                                            'href' => '/app/admin/demos?demo=system/file',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '文件管理',
                                            'value' => '60',
                                        ),
                                    6 =>
                                        array (
                                            'id' => 49,
                                            'title' => '登录日志',
                                            'icon' => 'layui-icon layui-icon-date',
                                            'key' => 'demo/system/login',
                                            'pid' => 54,
                                            'created_at' => '-0001-11-30 00:00:00',
                                            'updated_at' => '2023-12-12 16:14:25',
                                            'href' => '/app/admin/demos?demo=system/login',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '登录日志',
                                            'value' => '200',
                                        ),
                                    7 =>
                                        array (
                                            'id' => 50,
                                            'title' => '操作日志',
                                            'icon' => 'layui-icon layui-icon-survey',
                                            'key' => 'demo/system/option',
                                            'pid' => 54,
                                            'created_at' => '-0001-11-30 00:00:00',
                                            'updated_at' => '2023-12-12 16:14:29',
                                            'href' => '/app/admin/demos?demo=system/option',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '操作日志',
                                            'value' => '201',
                                        ),
                                ),
                        ),
                    7 =>
                        array (
                            'id' => 51,
                            'title' => '个人中心',
                            'icon' => 'layui-icon layui-icon-slider',
                            'key' => 'demo/enrollee',
                            'pid' => 18,
                            'created_at' => '2023-08-19 15:08:04',
                            'updated_at' => '2023-08-19 15:08:04',
                            'href' => '',
                            'type' => 0,
                            'weight' => 0,
                            'name' => '个人中心',
                            'value' => '61',
                            'children' =>
                                array (
                                    0 =>
                                        array (
                                            'id' => 52,
                                            'title' => '我的消息',
                                            'icon' => 'layui-icon layui-icon-email',
                                            'key' => 'demo/enrollee/message',
                                            'pid' => 61,
                                            'created_at' => '2023-08-19 15:08:03',
                                            'updated_at' => '2023-12-12 16:16:51',
                                            'href' => '/app/admin/demos?demo=enrollee/message',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '我的消息',
                                            'value' => '46',
                                        ),
                                    1 =>
                                        array (
                                            'id' => 53,
                                            'title' => '我的资料',
                                            'icon' => 'layui-icon layui-icon-username',
                                            'key' => 'demo/enrollee/profile',
                                            'pid' => 61,
                                            'created_at' => '2023-08-19 15:08:04',
                                            'updated_at' => '2023-08-19 15:08:04',
                                            'href' => '/app/admin/demos?demo=enrollee/profile',
                                            'type' => 1,
                                            'weight' => 0,
                                            'name' => '我的资料',
                                            'value' => '62',
                                        ),
                                ),
                        ),
                ),
        ),
); ?>